### ISSUE TITLE
Some conflicts with Scala library versions

### ISSUE THREAD

**Issue by justinhj** [sorm/sorm#65]
With the following as a library dependence I get some conflict with Scala binary version that I can't seem to fix. Could you let me know if you have a fix or suggestion? 

"org.sorm-framework" % "sorm" % "0.3.18"

Error ... 

3:49:32 PM SBT project import
           [warn] Binary version (2.12.0-M3) for dependency org.scala-lang#scala-compiler;2.12.0-M3
           [warn] 	in default#sorm-justin$sources_javadoc_2.11;1.0 differs from Scala binary version in project (2.11).
           [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
           [warn]  * org.scala-lang:scala-compiler:(2.12.0-M3, 2.11.7)
           [warn]  * org.scala-lang:scala-library:(2.11.7, 2.11.0)

**Comment by justinhj** [comment]
Not sure if it's related to the library version but I also get an error after the tables are created in the Db init function


java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction1
	at scala.tools.cmd.CommandLineParser$.tokenize(CommandLineParser.scala:65)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.arguments$lzycompute(ToolBoxFactory.scala:34)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.arguments(ToolBoxFactory.scala:34)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.virtualDirectory$lzycompute(ToolBoxFactory.scala:36)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.virtualDirectory(ToolBoxFactory.scala:35)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.classLoader$lzycompute(ToolBoxFactory.scala:31)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.classLoader(ToolBoxFactory.scala:31)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.mirror$lzycompute(ToolBoxFactory.scala:32)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.mirror(ToolBoxFactory.scala:32)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.parse(ToolBoxFactory.scala:414)
	at sorm.persisted.PersistedClass$.createClass(PersistedClass.scala:107)
	at sorm.persisted.PersistedClass$$anon$1$$anonfun$resolve$1.apply(PersistedClass.scala:125)
	at sorm.persisted.PersistedClass$$anon$1$$anonfun$resolve$1.apply(PersistedClass.scala:125)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at sorm.persisted.PersistedClass$$anon$1.resolve(PersistedClass.scala:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sorm.persisted.PersistedClass$.apply(PersistedClass.scala:129)
	at sorm.Instance$Initialization$$anonfun$9$$anonfun$apply$16.apply(Instance.scala:239)
	at sorm.Instance$Initialization$$anonfun$9$$anonfun$apply$16.apply(Instance.scala:239)
	at embrace.package$EmbraceAny$.$$extension(package.scala:6)
	at sorm.Instance$Initialization$$anonfun$9.apply(Instance.scala:239)
	at sorm.Instance$Initialization$$anonfun$9.apply(Instance.scala:239)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
	at sorm.Instance$Initialization.<init>(Instance.scala:239)
	at sorm.Instance.<init>(Instance.scala:38)
	at justong.Db$.<init>(main.scala:13)
	at justong.Db$.<clinit>(main.scala)
	at justong.Music$$anonfun$main$1.apply(main.scala:33)
	at justong.Music$$anonfun$main$1.apply(main.scala:32)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:181)
	at justong.Music$.main(main.scala:31)
	at justong.Music.main(main.scala)
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction1
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.parse(ToolBoxFactory.scala:414)
	at sorm.persisted.PersistedClass$.createClass(PersistedClass.scala:107)
	at sorm.persisted.PersistedClass$$anon$1$$anonfun$resolve$1.apply(PersistedClass.scala:125)
	at sorm.persisted.PersistedClass$$anon$1$$anonfun$resolve$1.apply(PersistedClass.scala:125)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at sorm.persisted.PersistedClass$$anon$1.resolve(PersistedClass.scala:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sorm.persisted.PersistedClass$.apply(PersistedClass.scala:129)
	at sorm.Instance$Initialization$$anonfun$9$$anonfun$apply$16.apply(Instance.scala:239)
	at sorm.Instance$Initialization$$anonfun$9$$anonfun$apply$16.apply(Instance.scala:239)
	at embrace.package$EmbraceAny$.$$extension(package.scala:6)
	at sorm.Instance$Initialization$$anonfun$9.apply(Instance.scala:239)
	at sorm.Instance$Initialization$$anonfun$9.apply(Instance.scala:239)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
	at sorm.Instance$Initialization.<init>(Instance.scala:239)
	at sorm.Instance.<init>(Instance.scala:38)
	at justong.Db$.<init>(main.scala:13)
	at justong.Db$.<clinit>(main.scala)
	at justong.Music$$anonfun$main$1.apply(main.scala:33)
	at justong.Music$$anonfun$main$1.apply(main.scala:32)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:181)
	at justong.Music$.main(main.scala:31)
	at justong.Music.main(main.scala)
Caused by: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction1
	... 27 more
Caused by: java.lang.ClassNotFoundException: scala.runtime.java8.JFunction1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

**Comment by justinhj** [comment]
http://stackoverflow.com/questions/32412430/error-while-starting-scala-project-that-uses-sorm-framework
