### ISSUE TITLE
Entity `Nothing` is not registered

### ISSUE THREAD

**Issue by kelebra** [sorm/sorm#67]
Hi, guys,

I am pretty much new to sorm framework and decided to try it because of its API simplicity but unfortunately get this exception during 'fetch by id' operation. Please provide some advice on code below:

```scala

  object Database extends Instance(
    entities = Set(Entity[Post]()),
    url = config.getString("db.url"),
    user = config.getString("db.user"),
    password = config.getString("db.password"),
    initMode = if (config.getBoolean("db.init")) InitMode.DropAllCreate else InitMode.DoNothing
  ) {}

```

```scala

import org.h2.tools.Server
import org.scalatest.{BeforeAndAfterAll, Matchers, WordSpec}

class DatabaseSpec extends WordSpec with Matchers with BeforeAndAfterAll {

  "Database" should {

    "provide value by id" in {
      val post = Post("title", "azaza")
      val saved = Database.save(post)
      println(Database.fetchById(saved.id))
    }
  }

  override protected def beforeAll(): Unit = Server.createTcpServer("-tcpAllowOthers").start()
}
```

Please find full stack trace below:

```scala
[info] - should provide value by id *** FAILED ***
[info]   sorm.core.SormException: Entity `Nothing` is not registered
[info]   at sorm.Instance$Api$$anonfun$mapping$1$1.apply(Instance.scala:57)
[info]   at sorm.Instance$Api$$anonfun$mapping$1$1.apply(Instance.scala:57)
[info]   at scala.Option.getOrElse(Option.scala:121)
[info]   at sorm.Instance$Api$class.mapping$1(Instance.scala:56)
[info]   at sorm.Instance$Api$class.sorm$Instance$Api$$mapping(Instance.scala:61)
[info]   at sorm.Instance$Api$$anonfun$fetchById$1$$anonfun$apply$10.apply(Instance.scala:117)
[info]   at sorm.Instance$Api$$anonfun$fetchById$1$$anonfun$apply$10.apply(Instance.scala:117)
[info]   at embrace.package$EmbraceAny$.$$extension(package.scala:6)
[info]   at sorm.Instance$Api$$anonfun$fetchById$1.apply(Instance.scala:117)
[info]   at sorm.Instance$Api$$anonfun$fetchById$1.apply(Instance.scala:116)
```

Thanks in advance,
Oleksii

**Comment by nikita-volkov** [comment]
What's the definition of `Post`?

**Comment by kelebra** [comment]
Post is just case class:
case class Post(title: String, content:String)

**Comment by nikita-volkov** [comment]
Hmm.. Which version of Scala are you using?

**Comment by kelebra** [comment]
2.11.7
