### ISSUE TITLE
Oracle driver not implemented

### ISSUE THREAD

**Issue by lauhin** [sorm/sorm#69]
Hi guys,

I tried to use sorm with an Oracle database. I got an error like:

`Exception in thread "main" scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
	at sorm.core.DbType$.driverClass(DbType.scala:42)`

When I took a closer look, the Oracle driver is not implemented.
In your method 'byUrl' in the 'DbType' object the oracle case exists:

`case u if u.startsWith("jdbc:oracle:") => Oracle`

But in the 'driverClass' method, there is not Oracle driver case... Is it possible to add the oracle case? The driver is:

`case DbType.Oracle    => "oracle.jdbc.driver.OracleDriver"`

Thanks guys!

Kind regards,

Laurent :-)

**Comment by clangguth** [comment]
Hi Laurent,

check out the newest version -- I just got PR #72 accepted :-)

Cheers
Chris
