### ISSUE TITLE
thread deadlock in sorm.mappings.ValueMapping.column$lzycompute

### ISSUE THREAD

**Issue by pjfanning** [sorm/sorm#80]
We're using scala 2.11.7. My understanding is that scala lazy val has a few issues in its underlying [implementation](https://blog.codecentric.de/en/2016/02/lazy-vals-scala-look-hood/).
Would it be possible to make columnType a val instead of a lazy val?
https://github.com/sorm/sorm/blob/master/src/main/scala/sorm/mappings/ValueMapping.scala

Also, there is a ??? unimplemented case that should throw an exception with an error message/

[18-Oct-2016 06:40:59.030 PDT] INFO [com.workday.dataeditor.common.metrics.ApplicationMetrics$] type=GAUGE, name=threads.deadlocks, value=[dataeditor-spray-akka.actor.default-dispatcher-22 locked on sorm.mappings.ValueMapping@69bfeb84 (owned by dataeditor-spray-akka.actor.default-dispatcher-23):
at sorm.mappings.ValueMapping.column$lzycompute(ValueMapping.scala:10)
at sorm.mappings.ValueMapping.column(ValueMapping.scala:10)
at sorm.mappings.ColumnMapping$class.columnsForContainer(ColumnMapping.scala:11)
at sorm.mappings.ValueMapping.columnsForContainer(ValueMapping.scala:10)
at sorm.mappings.CompositeMapping$$anonfun$compositeColumns$1.apply(CompositeMapping.scala:15)
at sorm.mappings.CompositeMapping$$anonfun$compositeColumns$1.apply(CompositeMapping.scala:15)
at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
at sorm.mappings.CompositeMapping$class.compositeColumns(CompositeMapping.scala:15)
at sorm.mappings.OptionToNullableMapping.compositeColumns$lzycompute(OptionToNullableMapping.scala:10)
at sorm.mappings.OptionToNullableMapping.compositeColumns(OptionToNullableMapping.scala:10)
at sorm.mappings.CompositeMapping$class.columnsForContainer(CompositeMapping.scala:16)
at sorm.mappings.OptionToNullableMapping.columnsForContainer(OptionToNullableMapping.scala:10)
at sorm.mappings.OptionToNullableMapping.valuesForContainerTableRow(OptionToNullableMapping.scala:28)
at sorm.mappings.EntityMapping$$anonfun$2.apply(EntityMapping.scala:57)
at sorm.mappings.EntityMapping$$anonfun$2.apply(EntityMapping.scala:57)
at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:497)

**Comment by nikita-volkov** [comment]
Thanks for your contribution. It's released in 0.3.21.

**Comment by pjfanning** [comment]
Thanks Nikita
